language: node_js
node_js: stable
before_install: 
  - openssl aes-256-cbc -K $encrypted_caccdbb369ac_key -iv $encrypted_caccdbb369ac_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar xzvf credentials.tar.gz
  - python2 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);' 
services: docker
after_success: ./deploy.sh

cache:
  directories:
  - $HOME/google-cloud-sdk

script:
  - rm -rf $HOME/google-cloud-sdk
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - curl https://sdk.cloud.google.com | bash
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components update kubectl